import Head from 'next/head';
import ContentList from '../lib/components/ContentList';
import { getBlogs } from '../lib/models/blogs';

import type { GetStaticProps, GetStaticPaths, GetServerSideProps } from 'next';


export const getServerSideProps: GetServerSideProps = async (context) => {

  return {
    props: {
      blogPosts: await getBlogs()
    }
  }
}


export default function Home({ blogPosts }) {
  return (
    <div>
      <Head>
        <title>Foolar Daily Blog - FDB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>



      <ContentList blogPosts={blogPosts} />

    </div>
  )
}
