import Head from 'next/head';
import ContentList from '../lib/components/ContentList';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Foolar Daily Blog - FDB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>



      <ContentList />

    </div>
  )
}
